version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: dispatch_api
    ports:
      - "${PORT:-3000}:3000"
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://mongo:27017/dispatch_engine
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dispatch_net

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    container_name: dispatch_worker
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://mongo:27017/dispatch_engine
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dispatch_net

  redis:
    image: redis:7-alpine
    container_name: dispatch_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - dispatch_net

  mongo:
    image: mongo:7
    container_name: dispatch_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - dispatch_net

volumes:
  redis_data:
  mongo_data:

networks:
  dispatch_net:
    driver: bridge
